### PR TITLE
Parse attribute syntax

### LINKED ISSUE #60: New attribute syntax
Hello!

A new syntax has been added to Gleam, the attribute syntax

```gleam
@target(erlang)
pub fn main() { todo }
```

Attributes proceed imports or definitions in modules. The compiler only accepts `@target(erlang)` and `@target(javascript)` but I believe the tree sitter should accept any name that would be a valid function name in place of `target` and any comma-delimited sequence of optionally labelled constant expressions within the `()`.

```gleam
@deprecated(since: "1.2.0", replacement: wobble)
pub fn wibble() { todo }
```

### PR DESCRIPTION
**Pull request by the-mikedavis**
Closes #60.

I didn't add a requirement that attributes preceed imports or functions but I think it's probably ok if we're a little more permissive about that. I'm happy to add some extra checks if that's desired though.

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Looks great! Thank you

**Comment by lpil** [comment]
Hey folks! Is there anything blocking merging and releasing these?

**Comment by the-mikedavis** [comment]
Should we focus on merging #55 first and cutting a 0.28 release before merging the newer syntax change PRs @J3RN? I could take a look at fixing the integration tests if you'd like.

**Comment by J3RN** [comment]
@the-mikedavis Agreed, I'm going to take care of a few items now.  I'd like to sequence the updates in an order that makes sense and cut relevant releases.  As for the integration tests, I'm going to undo the dropping of `try` for *now*, with that update to be shipped with v0.31.0.

**Pull request merged**
