### PR TITLE
Add support for v0.21.0 (aka add bang negation)

### PR DESCRIPTION
**Pull request by J3RN**
A bit belated :sweat_smile: 

From the [diff of the Gleam parser](https://github.com/gleam-lang/gleam/compare/v0.20.1...v0.21.0#diff-7e7f48f9f3e05faed95a701f8ab2ce2c0a718e8fdf5f897dc8fa36282a51649a), it appears that the only differences from 0.20.1 to 0.21.0 are
- Add the negation operator
- Parsing failure hints

As such, this change just adds support for the negation operator.

cc @the-mikedavis

### CODE REVIEW

**Comment by the-mikedavis** [comment]
It may make sense to categorize this as a unary operator if there are many others. `-` as in `-1` comes to mind from other languages. [tree-sitter-elixir](https://github.com/elixir-lang/tree-sitter-elixir/blob/5d0c1bfcdf8aaad225525acad930a972b319a675/grammar.js#L847-L863) has a somewhat complicated unary operator rule helper function (complicated because of the precedence). I have a simpler version in [tree-sitter-erlang](https://github.com/the-mikedavis/tree-sitter-erlang/blob/bc94fb0687e9135c39be474fe53c3be8fa3461c4/grammar.js#L468-L473) that could be a good reference. It seems like unary operators are not (yet) common in gleam though so I don't think it's necessary - just something to keep in mind for later.

**Review by the-mikedavis — APPROVED** [review]
🥳 :shipit:

**Comment by lpil** [comment]
If it helps I've no plans to add any new unary operators

**Comment by J3RN** [comment]
@the-mikedavis You raise a good point! Having a clause/function for unary operators did cross my mind, but in general I try to hew as close to the Gleam parser as possible (makes updates like this one easier). Perhaps if more unary operators are added, we can reconsider.

Cheers all! :tada:

**Pull request merged**
